settings:
  headless: false
  browser: "chromium"
  viewport:
    width: 1920
    height: 1080
  zoom_level: 1.0

authentication:
  enabled: true
  # Đường dẫn đến tệp cookie của bạn.
  # Tệp này phải tồn tại và còn hiệu lực.
  profile_path: "cookies/facebook_session.json"

workflow:
  - action: "goto"
    params:
      url: "https://www.facebook.com"
    description: "Truy cập Facebook bằng cookie"

  - action: "wait"
    params:
      milliseconds: 7000
    description: "Chờ trang tải xong"

  - action: "click"
    params:
      x: 36
      y: 99
    description: "Click vào tọa độ (36, 99)"

  - action: "wait"
    params:
      milliseconds: 3000
    description: "Chờ sau khi click"

  - action: "screenshot"
    params:
      path: "screenshots/click_result.png"
    description: "Chụp ảnh kết quả"